#!/usr/bin/env bash
# PATH: setup-system.sh
# =============================================================================
# setup-system.sh (SYSTEM INTEGRATION v39.9)
# =============================================================================
# WHAT: one-shot system integration run at server start and after cold-start.
#       Writes sudoers, blacklist, dracut config, modules-load, and firmware
#       so that Wi-Fi works at boot without any manual intervention.
#
# WHY: four confirmed gaps from session 2026-04-04:
#   1. No blacklist for brcmsmac/brcmfmac -- brcmsmac intercepted every
#      modprobe b43 call (confirmed: 29 dmesg lines "brcmsmac: unknown parameter")
#   2. No dracut config -- firmware installed to /usr/lib/firmware/b43 after
#      last initramfs build, so b43 failed at boot with error -2 (ENOENT)
#      even though files existed on disk (confirmed from boot dmesg)
#   3. No modules-load.d entry -- b43 load order not guaranteed at boot
#   4. sudoers bootstrap catch-22 -- sudo tee required sudo to write itself
#
# MENTAL MODEL BEFORE: brcmsmac loads at boot, claims BCM4331, b43 cannot bind,
#   WIFI-HW shows "missing", fix-wifi.sh exits early because ethernet is healthy
# MENTAL MODEL AFTER: brcmsmac blacklisted, b43 in modules-load.d, firmware in
#   initramfs, b43 binds at boot, wlp2s0b1 appears, WIFI-HW shows "enabled"
#
# FAILURE MODE: dracut step requires root -- if not root and sudo unavailable,
#   dracut is skipped with a warning; Wi-Fi will still work post-boot via
#   fix-wifi.service but not at boot time until dracut is run manually
#
# VERIFIES WITH: after reboot, nmcli radio shows WIFI-HW: enabled without
#   any manual intervention; lsinitrd | grep b43 shows firmware files

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/broadcom-control"
BLACKLIST_FILE="/etc/modprobe.d/broadcom-bcm4331.conf"
DRACUT_FILE="/etc/dracut.conf.d/b43-firmware.conf"
MODULES_LOAD_FILE="/etc/modules-load.d/b43.conf"

echo "[SETUP] Starting system integration in $PROJECT_ROOT"

# ── 1. Chmod all scripts ────────────────────────────────────────────────────
echo "[SETUP] Setting executable permissions on scripts."
chmod +x "${PROJECT_ROOT}"/*.sh

# ── 2. Resolve binary paths ─────────────────────────────────────────────────
RFKILL_PATH=$(command -v rfkill || echo "/usr/sbin/rfkill")
MODPROBE_PATH=$(command -v modprobe || echo "/usr/sbin/modprobe")
NMCLI_PATH=$(command -v nmcli || echo "/usr/bin/nmcli")
SYSTEMCTL_PATH=$(command -v systemctl || echo "/usr/bin/systemctl")
TEE_PATH=$(command -v tee || echo "/usr/bin/tee")
TCPDUMP_PATH=$(command -v tcpdump || echo "/usr/sbin/tcpdump")
LSPCI_PATH=$(command -v lspci || echo "/usr/sbin/lspci")
UDEVADM_PATH=$(command -v udevadm || echo "/usr/sbin/udevadm")
JOURNALCTL_PATH=$(command -v journalctl || echo "/usr/bin/journalctl")
DMESG_PATH=$(command -v dmesg || echo "/usr/bin/dmesg")
DRACUT_PATH=$(command -v dracut || echo "/usr/bin/dracut")
MODINFO_PATH=$(command -v modinfo || echo "/usr/sbin/modinfo")
RMMOD_PATH=$(command -v rmmod || echo "/usr/sbin/rmmod")
IP_PATH=$(command -v ip || echo "/usr/sbin/ip")
FIX_WIFI_PATH="${PROJECT_ROOT}/fix-wifi.sh"
BENCH_PATH="${PROJECT_ROOT}/network_sniff_bench.sh"
DAEMON_PATH="${PROJECT_ROOT}/network_autonomous_daemon.sh"

SUDOERS_CONTENT="# Broadcom BCM4331 Forensic Controller (Unified v39.9)
# Generated by setup-system.sh on $(date)
# Includes dracut, rmmod, ip for Wi-Fi recovery without password prompts
$(whoami) ALL=(ALL) NOPASSWD: $RFKILL_PATH, $MODPROBE_PATH, $RMMOD_PATH, $NMCLI_PATH, $SYSTEMCTL_PATH, $TEE_PATH /etc/resolv.conf, $TCPDUMP_PATH, $LSPCI_PATH, $UDEVADM_PATH, $JOURNALCTL_PATH, $DMESG_PATH, $DRACUT_PATH, $MODINFO_PATH, $IP_PATH, $FIX_WIFI_PATH, $BENCH_PATH, $DAEMON_PATH"

# ── 3. Write sudoers ────────────────────────────────────────────────────────
echo "[SETUP] Generating sudoers drop-in for non-interactive forensics."
if [[ "$EUID" -eq 0 ]]; then
    mkdir -p /etc/sudoers.d
    echo "$SUDOERS_CONTENT" > "$SUDOERS_FILE"
    chmod 440 "$SUDOERS_FILE"
    visudo -c -f "$SUDOERS_FILE" || { echo "[WARN] sudoers syntax error -- removing"; rm -f "$SUDOERS_FILE"; }
else
    echo "$SUDOERS_CONTENT" | sudo tee "$SUDOERS_FILE" > /dev/null
    sudo chmod 440 "$SUDOERS_FILE"
    sudo visudo -c -f "$SUDOERS_FILE" || { echo "[WARN] sudoers syntax error -- removing"; sudo rm -f "$SUDOERS_FILE"; }
fi
echo "[SETUP] Sudoers written and validated."

# ── 4. Write brcmsmac/brcmfmac blacklist ────────────────────────────────────
# WHY: brcmsmac aliases match BCM4331 PCI ID [14e4:4331] before b43 in the
#      module alias table. Confirmed from dmesg: every modprobe b43 attempt
#      loaded brcmsmac instead (29 lines "brcmsmac: unknown parameter allhwsupport").
#      brcmfmac blacklisted as additional precaution -- it also matches bcma devices.
echo "[SETUP] Writing brcmsmac/brcmfmac blacklist."
BLACKLIST_CONTENT="# BCM4331: blacklist competing drivers so b43 can bind
# Confirmed cause: brcmsmac intercepted modprobe b43 allhwsupport=1 (session 2026-04-04)
blacklist brcmsmac
blacklist brcmfmac
# b43 options: allhwsupport=1 required for BCM4331 rev 02 (confirmed from dmesg)
options b43 allhwsupport=1"

if [[ "$EUID" -eq 0 ]]; then
    echo "$BLACKLIST_CONTENT" > "$BLACKLIST_FILE"
else
    echo "$BLACKLIST_CONTENT" | sudo tee "$BLACKLIST_FILE" > /dev/null
fi
echo "[SETUP] Blacklist written: $BLACKLIST_FILE"

# ── 5. Write modules-load.d entry ───────────────────────────────────────────
# WHY: without modules-load.d, b43 load order at boot is not guaranteed.
#      b43.conf created during session but not present at prior boots.
echo "[SETUP] Writing b43 to modules-load.d."
if [[ "$EUID" -eq 0 ]]; then
    echo "b43" > "$MODULES_LOAD_FILE"
else
    echo "b43" | sudo tee "$MODULES_LOAD_FILE" > /dev/null
fi
echo "[SETUP] modules-load.d written: $MODULES_LOAD_FILE"

# ── 6. Write dracut firmware config ─────────────────────────────────────────
# WHY: b43 firmware at /usr/lib/firmware/b43 was installed after the last
#      initramfs build. Boot-time b43 load failed with error -2 (ENOENT) even
#      though files existed on disk -- they were not in the initramfs.
#      Confirmed fix: dracut --force rebuilt initramfs, included firmware,
#      and b43 loaded successfully at next boot (confirmed: wlp2s0b1 connected).
#      This dracut.conf.d entry ensures firmware is included on every future
#      kernel update without manual intervention.
echo "[SETUP] Writing dracut firmware config."
DRACUT_CONTENT='# BCM4331: include b43 firmware in initramfs
# Without this, b43 fails at boot with error -2 (ENOENT) on firmware load
# even when files exist at /usr/lib/firmware/b43 -- they are not in the image
# Confirmed fix: dracut --force + modprobe bcma && modprobe b43 (session 2026-04-04)
install_items+=" /usr/lib/firmware/b43/ucode29_mimo.fw "
install_items+=" /usr/lib/firmware/b43/ht0initvals29.fw "
install_items+=" /usr/lib/firmware/b43/ht0bsinitvals29.fw "
add_drivers+=" b43 bcma ssb "'

if [[ "$EUID" -eq 0 ]]; then
    mkdir -p /etc/dracut.conf.d
    echo "$DRACUT_CONTENT" > "$DRACUT_FILE"
else
    sudo mkdir -p /etc/dracut.conf.d
    echo "$DRACUT_CONTENT" | sudo tee "$DRACUT_FILE" > /dev/null
fi
echo "[SETUP] Dracut config written: $DRACUT_FILE"

# ── 7. Rebuild initramfs if firmware files exist ─────────────────────────────
# WHY: dracut config alone does not take effect until dracut runs.
#      Run it now if firmware is present. Skip if firmware missing -- prepare-bundle.sh
#      must run first in that case.
if ls /usr/lib/firmware/b43/*.fw >/dev/null 2>&1; then
    INITRAMFS="/boot/initramfs-$(uname -r).img"
    NEWEST_FW=$(ls -t /usr/lib/firmware/b43/*.fw | head -1)
    if [[ ! -f "$INITRAMFS" ]] || [[ "$NEWEST_FW" -nt "$INITRAMFS" ]]; then
        echo "[SETUP] Firmware newer than initramfs -- rebuilding."
        if [[ "$EUID" -eq 0 ]]; then
            dracut --force 2>&1 | tail -5
        else
            sudo dracut --force 2>&1 | tail -5
        fi
        echo "[SETUP] Initramfs rebuilt."
    else
        echo "[SETUP] Initramfs is current -- skipping dracut rebuild."
    fi
else
    echo "[SETUP] WARN: /usr/lib/firmware/b43 firmware missing -- run prepare-bundle.sh first."
    echo "[SETUP] WARN: initramfs not rebuilt. Wi-Fi will work post-boot but not at boot time."
fi

# ── 8. SELinux context for scripts ─────────────────────────────────────────────
# WHY: SELinux denies init_t (systemd) executing user_home_t files.
#      Confirmed: 14 AVC denied execute entries in audit.log (session 2026-04-04).
#      fix-wifi.service and network_autonomous_daemon.sh both blocked until labeled.
#      semanage fcontext persists across restorecon and git checkout operations.
echo "[SETUP] Applying SELinux bin_t context to project scripts."
if command -v semanage >/dev/null 2>&1; then
    SEMANAGE_RULE="${PROJECT_ROOT}/.*\.sh"
    if ! sudo semanage fcontext -l | grep -q "$PROJECT_ROOT"; then
        sudo semanage fcontext -a -t bin_t "$SEMANAGE_RULE" 2>/dev/null || true
    fi
    sudo restorecon -q "${PROJECT_ROOT}"/*.sh 2>/dev/null || true
    echo "[SETUP] SELinux context applied."
else
    echo "[SETUP] WARN: semanage not found -- SELinux context not set. Install policycoreutils-python-utils."
fi

# ── 8. Initialize database and log ──────────────────────────────────────────
[[ ! -f "${PROJECT_ROOT}/config_db.jsonl" ]] && touch "${PROJECT_ROOT}/config_db.jsonl"
[[ ! -f "${PROJECT_ROOT}/verbatim_handshake.log" ]] && touch "${PROJECT_ROOT}/verbatim_handshake.log"

echo "[SETUP] System integration complete."