#!/usr/bin/env bash

# =============================================================================
# setup-system.sh (SYSTEM INTEGRATION v39.8)
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/broadcom-control"

echo "[SETUP] Starting system integration in $PROJECT_ROOT"

# 1. Chmod all scripts
echo "[SETUP] Setting executable permissions on scripts."
chmod +x "${PROJECT_ROOT}"/*.sh

# 2. Generate Sudoers Drop-in
echo "[SETUP] Generating sudoers drop-in for non-interactive forensics."
SUDOERS_CONTENT=$(cat <<EOF
# Broadcom BCM4331 Forensic Controller (Unified v39.8)
# Generated by setup-system.sh on $(date)
$(whoami) ALL=(ALL) NOPASSWD: /usr/sbin/rfkill, /usr/sbin/modprobe, /usr/bin/nmcli, /usr/bin/systemctl, /usr/bin/tee /etc/resolv.conf
EOF
)

if [[ "$EUID" -eq 0 ]]; then
    echo "$SUDOERS_CONTENT" > "$SUDOERS_FILE"
    chmod 440 "$SUDOERS_FILE"
else
    echo "$SUDOERS_CONTENT" | sudo tee "$SUDOERS_FILE" > /dev/null
    sudo chmod 440 "$SUDOERS_FILE"
fi

# 3. Initialize Database
if [[ ! -f "${PROJECT_ROOT}/config_db.jsonl" ]]; then
    echo "[SETUP] Initializing configuration database."
    touch "${PROJECT_ROOT}/config_db.jsonl"
fi

# 4. Initialize Log
if [[ ! -f "${PROJECT_ROOT}/verbatim_handshake.log" ]]; then
    echo "[SETUP] Initializing forensic log."
    touch "${PROJECT_ROOT}/verbatim_handshake.log"
fi

echo "[SETUP] System integration complete."
