#!/usr/bin/env bash

# =============================================================================
# setup-system.sh (SYSTEM INTEGRATION v39.8)
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/broadcom-control"

echo "[SETUP] Starting system integration in $PROJECT_ROOT"

# 1. Chmod all scripts
echo "[SETUP] Setting executable permissions on scripts."
chmod +x "${PROJECT_ROOT}"/*.sh

# 2. Generate Sudoers Drop-in
echo "[SETUP] Generating sudoers drop-in for non-interactive forensics."

# Resolve paths dynamically
RFKILL_PATH=$(command -v rfkill || echo "/usr/sbin/rfkill")
MODPROBE_PATH=$(command -v modprobe || echo "/usr/sbin/modprobe")
NMCLI_PATH=$(command -v nmcli || echo "/usr/bin/nmcli")
SYSTEMCTL_PATH=$(command -v systemctl || echo "/usr/bin/systemctl")
TEE_PATH=$(command -v tee || echo "/usr/bin/tee")
TCPDUMP_PATH=$(command -v tcpdump || echo "/usr/sbin/tcpdump")
LSPCI_PATH=$(command -v lspci || echo "/usr/sbin/lspci")
UDEVADM_PATH=$(command -v udevadm || echo "/usr/sbin/udevadm")
JOURNALCTL_PATH=$(command -v journalctl || echo "/usr/bin/journalctl")
DMESG_PATH=$(command -v dmesg || echo "/usr/bin/dmesg")
FIX_WIFI_PATH="${PROJECT_ROOT}/fix-wifi.sh"

SUDOERS_CONTENT=$(cat <<EOF
# Broadcom BCM4331 Forensic Controller (Unified v39.8)
# Generated by setup-system.sh on $(date)
$(whoami) ALL=(ALL) NOPASSWD: $RFKILL_PATH, $MODPROBE_PATH, $NMCLI_PATH, $SYSTEMCTL_PATH, $TEE_PATH /etc/resolv.conf, $TCPDUMP_PATH, $LSPCI_PATH, $UDEVADM_PATH, $JOURNALCTL_PATH, $DMESG_PATH, $FIX_WIFI_PATH
EOF
)

if [[ "$EUID" -eq 0 ]]; then
    mkdir -p /etc/sudoers.d || echo "[WARN] Could not create /etc/sudoers.d"
    if [[ -d /etc/sudoers.d ]]; then
        echo "$SUDOERS_CONTENT" > "$SUDOERS_FILE"
        chmod 440 "$SUDOERS_FILE"
    fi
else
    if command -v sudo >/dev/null 2>&1; then
        sudo mkdir -p /etc/sudoers.d || true
        echo "$SUDOERS_CONTENT" | sudo tee "$SUDOERS_FILE" > /dev/null
        sudo chmod 440 "$SUDOERS_FILE"
    else
        echo "[WARN] sudo not found, skipping sudoers generation."
    fi
fi

# 3. Initialize Database
if [[ ! -f "${PROJECT_ROOT}/config_db.jsonl" ]]; then
    echo "[SETUP] Initializing configuration database."
    touch "${PROJECT_ROOT}/config_db.jsonl"
fi

# 4. Initialize Log
if [[ ! -f "${PROJECT_ROOT}/verbatim_handshake.log" ]]; then
    echo "[SETUP] Initializing forensic log."
    touch "${PROJECT_ROOT}/verbatim_handshake.log"
fi

echo "[SETUP] System integration complete."
